FROM node:22-alpine

WORKDIR /app

RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml ./
COPY tsconfig.json tsconfig.build.json nest-cli.json .prettierrc ./

RUN pnpm install --frozen-lockfile

COPY libs/common/ ./libs/common/
COPY libs/proto/ ./libs/proto/
COPY apps/kyc/ ./apps/kyc/

EXPOSE 4004
EXPOSE 50053

CMD ["pnpm", "run", "dev:kyc"]
