name: "mint_dev"

services:
  nginx:
    image: nginx:1.29-alpine
    container_name: mint-nginx
    networks: [mint]
    ports:
      - "80:80"
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth
      - wallet
    restart: on-failure
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost/health"]
      interval: 10s
      timeout: 3s
      retries: 3

  auth:
    build:
      context: .
      dockerfile: services/auth/Dockerfile
    container_name: mint-auth
    networks: [mint]
    ports:
      - "4001:4001"
    environment:
      ENV_FILENAME: ".env.development"
    volumes:
      - ./services/auth/src:/app/services/auth/src
      - ./shared-py:/app/shared-py
      - ./services/auth/.env.development:/app/services/auth/.env.development
    restart: on-failure

  wallet:
    build:
      context: .
      dockerfile: services/wallet/Dockerfile
    container_name: mint-wallet
    networks: [mint]
    ports:
      - "4002:4002"
    environment:
      ENV_FILENAME: ".env.development"
    volumes:
      - ./services/wallet/src:/app/services/wallet/src
      - ./shared-py:/app/shared-py
      - ./services/wallet/.env.development:/app/services/wallet/.env.development
    restart: on-failure

networks:
  mint:
    driver: bridge
