"""migration

Revision ID: b971775e308c
Revises: 
Create Date: 2026-03-21 01:08:59.771074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b971775e308c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fastauth_roles',
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('fastauth_users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fastauth_users_email'), 'fastauth_users', ['email'], unique=True)
    op.create_table('fastauth_oauth_accounts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('provider_account_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['fastauth_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fastauth_passkeys',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('public_key', sa.LargeBinary(), nullable=False),
    sa.Column('sign_count', sa.Integer(), nullable=False),
    sa.Column('aaguid', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['fastauth_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fastauth_passkeys_user_id'), 'fastauth_passkeys', ['user_id'], unique=False)
    op.create_table('fastauth_role_permissions',
    sa.Column('role_name', sa.String(), nullable=False),
    sa.Column('permission', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['role_name'], ['fastauth_roles.name'], ),
    sa.PrimaryKeyConstraint('role_name', 'permission')
    )
    op.create_table('fastauth_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['fastauth_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fastauth_tokens',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('token_type', sa.String(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['fastauth_users.id'], ),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index(op.f('ix_fastauth_tokens_user_id'), 'fastauth_tokens', ['user_id'], unique=False)
    op.create_table('fastauth_user_roles',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('role_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['role_name'], ['fastauth_roles.name'], ),
    sa.ForeignKeyConstraint(['user_id'], ['fastauth_users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fastauth_user_roles')
    op.drop_index(op.f('ix_fastauth_tokens_user_id'), table_name='fastauth_tokens')
    op.drop_table('fastauth_tokens')
    op.drop_table('fastauth_sessions')
    op.drop_table('fastauth_role_permissions')
    op.drop_index(op.f('ix_fastauth_passkeys_user_id'), table_name='fastauth_passkeys')
    op.drop_table('fastauth_passkeys')
    op.drop_table('fastauth_oauth_accounts')
    op.drop_index(op.f('ix_fastauth_users_email'), table_name='fastauth_users')
    op.drop_table('fastauth_users')
    op.drop_table('fastauth_roles')
    # ### end Alembic commands ###
