http:
  port: 4000

apiEndpoints:
  auth:
    host: '*'
    paths:
      - '/api/auth/*'
      - '/api/users/*'

  wallet:
    host: '*'
    paths: '/api/wallet/*'

  transaction:
    host: '*'
    paths: '/api/transactions/*'

serviceEndpoints:
  authService:
    url: 'http://auth_service:4001'

  walletService:
    url: 'http://wallet_service:4002'

  transactionService:
    url: 'http://transaction_service:4003'

policies:
  - rate-limit
  - proxy
  - cors

pipelines:
  authPipeline:
    apiEndpoints: [auth]
    policies:
      - rate-limit:
          - action:
              max: 50
              windowMs: 60000
              message: "Too many auth requests. Please slow down."
              key: req.ip
              headers:
                limit: X-RateLimit-Limit
                remaining: X-RateLimit-Remaining
                reset: X-RateLimit-Reset
      - cors:
        - action:
            origin: http://localhost:3000
            credentials: true
            methods: '*'
      - proxy:
          - action:
              serviceEndpoint: authService
              changeOrigin: true

  walletPipeline:
    apiEndpoints: [wallet]
    policies:
      - rate-limit:
          - action:
              max: 50
              windowMs: 60000
              message: "Too many auth requests. Please slow down."
              key: req.ip
              headers:
                limit: X-RateLimit-Limit
                remaining: X-RateLimit-Remaining
                reset: X-RateLimit-Reset
      - cors:
        - action:
            origin: http://localhost:3000
            credentials: true
            methods: '*'
      - proxy:
          - action:
              serviceEndpoint: walletService
              changeOrigin: true

  transactionPipeline:
    apiEndpoints: [transaction]
    policies:
      - cors:
        - action:
            origin: http://localhost:3000
            credentials: true
            methods: '*'
      - rate-limit:
          - action:
              max: 10
              windowMs: 60000
              message: "Too many transactions. Please slow down."
              key: req.ip
              headers:
                limit: X-RateLimit-Limit
                remaining: X-RateLimit-Remaining
                reset: X-RateLimit-Reset
      - proxy:
          - action:
              serviceEndpoint: transactionService
              changeOrigin: true
