http:
  port: 4000

apiEndpoints:
  auth:
    host: '*'
    paths: '/api/auth/*'

  wallet:
    host: '*'
    paths: '/api/wallet/*'

  transaction:
    host: '*'
    paths: '/api/transactions/*'

serviceEndpoints:
  authService:
    url: 'http://localhost:4001'

  walletService:
    url: 'http://localhost:4002'

  transactionService:
    url: 'http://localhost:4003'

policies:
  - rate-limit
  - proxy

pipelines:
  authPipeline:
    apiEndpoints: [auth]
    policies:
      - rate-limit:
          - action:
              max: 10
              windowMs: 60000
              message: "Too many auth requests. Please slow down."
              key: req.ip
              headers:
                limit: X-RateLimit-Limit
                remaining: X-RateLimit-Remaining
                reset: X-RateLimit-Reset
      - proxy:
          - action:
              serviceEndpoint: authService
              changeOrigin: true

  walletPipeline:
    apiEndpoints: [wallet]
    policies:
      - proxy:
          - action:
              serviceEndpoint: walletService
              changeOrigin: true

  transactionPipeline:
    apiEndpoints: [transaction]
    policies:
      - rate-limit:
          - action:
              max: 10
              windowMs: 60000
              message: "Too many transactions. Please slow down."
              key: req.ip
              headers:
                limit: X-RateLimit-Limit
                remaining: X-RateLimit-Remaining
                reset: X-RateLimit-Reset
      - proxy:
          - action:
              serviceEndpoint: transactionService
              changeOrigin: true
