"""migration

Revision ID: 50becfb77dd8
Revises: ed93e7a28d1a
Create Date: 2026-03-18 20:53:43.039661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50becfb77dd8'
down_revision: Union[str, Sequence[str], None] = 'ed93e7a28d1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balance_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('wallet_id', sa.String(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('delta', sa.BIGINT(), nullable=False),
    sa.Column('balance_after', sa.BIGINT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('balance_history')
    # ### end Alembic commands ###
