FROM python:3.12-slim

ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN apt-get update -y && \
    apt-get upgrade -y && \
    rm -rf /var/lib/apt/lists/*

COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv

WORKDIR /app

COPY pyproject.toml uv.lock ./
COPY shared-py/ shared-py/
COPY apps/wallet/pyproject.toml apps/wallet/README.md apps/wallet/
COPY libs/proto/wallet.proto libs/proto/wallet.proto
COPY scripts/generate_proto.py scripts/generate_proto.py

RUN uv sync --package mint-wallet --no-install-project --frozen

COPY apps/wallet/src/ apps/wallet/src/
COPY apps/wallet/alembic.ini apps/wallet/alembic.ini

RUN uv sync --package mint-wallet --frozen
RUN uv run python /app/scripts/generate_proto.py

WORKDIR /app/apps/wallet

EXPOSE 4002
EXPOSE 50051

CMD ["uv", "run", "dev"]
